//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GravityForceXEdit.rc
//
#define IDR_VERSION                     1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_GF10TYPE                    129
#define IDD_LOGDLG                      130
#define IDD_NAMEDLG                     131
#define IDD_SELECT_STRING               132
#define IDD_SCENEGRAPHDLG               133
#define IDD_COMPONENTLIBRARYDLG         134
#define IDD_PROPERTIESDLG               135
#define IDD_EDIT_PRS                    136
#define IDD_EDIT_LIGHT                  137
#define IDD_EDIT_WORLDOBJECT            138
#define IDD_EDIT_MODEL                  139
#define IDD_EDIT_BOUNDINGBOX            140
#define IDD_EDIT_LANDSCAPE              141
#define IDD_PROGRESS                    142
#define IDB_DRAG1                       143
#define IDB_DRAG1MASK                   144
#define IDB_FOLDER                      145
#define IDB_WHEEL                       146
#define IDD_EDITMODELMAP                149
#define IDD_EDIT_SHIP                   150
#define IDD_EDIT_BASE                   151
#define IDI_ICON1                       151
#define IDD_EDIT_AMMO                   152
#define IDD_EDIT_INDESTRUCTABLEREGION   154
#define IDD_EDIT_TURRET                 155
#define IDD_EDIT_WATER                  156
#define IDC_LOGLIST                     1000
#define IDC_NAMEEDIT                    1001
#define IDC_STRINGLIST                  1002
#define IDC_SCENEGRAPH_TREE             1003
#define IDC_COMPONENTLIBRARY_LIST       1004
#define IDC_PROPERTIES_TAB              1005
#define IDC_WO_NAME                     1006
#define IDC_WO_VISIBLE                  1007
#define IDC_WO_SCRIPTABLE               1008
#define IDC_WO_CODEEDIT                 1009
#define IDC_WO_UPDATEBUTTON             1010
#define IDC_WO_STATUS                   1011
#define IDC_PRS_XPOS                    1012
#define IDC_PRS_XPOSBUT                 1013
#define IDC_PRS_YPOS                    1014
#define IDC_PRS_YPOSBUT                 1015
#define IDC_PRS_ZPOS                    1016
#define IDC_PRS_ZPOSBUT                 1017
#define IDC_PRS_XROT                    1018
#define IDC_PRS_XROTBUT                 1019
#define IDC_PRS_YROT                    1020
#define IDC_PRS_YROTBUT                 1021
#define IDC_PRS_ZROT                    1022
#define IDC_PRS_ZROTBUT                 1023
#define IDC_PRS_XSIZE                   1024
#define IDC_PRS_XSCALE                  1025
#define IDC_PRS_XSIZEBUT                1026
#define IDC_PRS_XSCALEBUT               1027
#define IDC_PRS_YSIZE                   1028
#define IDC_PRS_YSCALE                  1029
#define IDC_PRS_YSIZEBUT                1030
#define IDC_PRS_YSCALEBUT               1031
#define IDC_PRS_ZSIZE                   1032
#define IDC_PRS_ZSCALE                  1033
#define IDC_PRS_ZSIZEBUT                1034
#define IDC_PRS_ZSCALEBUT               1035
#define IDC_BB_XSIZE                    1036
#define IDC_BB_XSIZEBUT                 1037
#define IDC_BB_XSIZEMAX                 1038
#define IDC_BB_XSIZEBUTMAX              1039
#define IDC_BB_YSIZE                    1040
#define IDC_BB_YSIZEBUT                 1041
#define IDC_BB_YSIZEMAX                 1042
#define IDC_BB_YSIZEBUTMAX              1043
#define IDC_BB_ZSIZE                    1044
#define IDC_BB_ZSIZEBUT                 1045
#define IDC_MODEL_SELECTMESH            1045
#define IDC_BB_ZSIZEMAX                 1046
#define IDC_MODEL_MESHFILENAME          1046
#define IDC_BB_ZSIZEBUTMAX              1047
#define IDC_MODEL_SELECTTEXTURE         1047
#define IDC_MODEL_TEXTUREFILENAME       1048
#define IDC_MODEL_SELECTCOLOUR          1049
#define IDC_MODEL_COLOUR                1050
#define IDC_MODEL_TRANSPARENCY          1051
#define IDC_PROGRESSBAR                 1052
#define IDC_INITIAL_ROTATION            1052
#define IDC_LIGHT_AMBIENT               1053
#define IDC_MAX_SPEED                   1053
#define IDC_LIGHT_TYPE                  1054
#define IDC_MAX_ACCEL                   1054
#define IDC_LIGHT_ATTENUATION0          1055
#define IDC_ROTATIONAL_VELOCITY         1055
#define IDC_LIGHT_ATTENUATION1          1056
#define IDC_ACCELERATION                1056
#define IDC_LIGHT_PHI                   1057
#define IDC_HEIGHT_OFFSET               1057
#define IDC_LIGHT_AMBIENTCOLOUR         1058
#define IDC_BULLETMODEL_SELECTMESH      1058
#define IDC_LIGHT_DIFFUSE               1059
#define IDC_BULLETMODEL_MESHFILENAME    1059
#define IDC_LIGHT_DIFFUSECOLOUR         1060
#define IDC_BULLETMODEL_SELECTTEXTURE   1060
#define IDC_LIGHT_SPECULARCOLOUR        1061
#define IDC_BULLETMODEL_TEXTUREFILENAME 1061
#define IDC_LIGHT_SPECULAR              1062
#define IDC_MODEL_SELECTCOLOUR2         1062
#define IDC_BULLETMODEL_SELECTCOLOUR    1062
#define IDC_LIGHT_RANGE                 1063
#define IDC_BULLETMODEL_COLOUR          1063
#define IDC_LANDSCAPE_SELECTHEIGHTMAP   1064
#define IDC_FUEL_USAGE                  1064
#define IDC_LANDSCAPE_SELECTCOLOURMAP   1065
#define IDC_LANDSCAPE_HEIGHTMAPFILENAME 1066
#define IDC_LANDSCAPE_COLOURMAPFILENAME 1067
#define IDC_LANDSCAPE_WIDTH             1068
#define IDC_LANDSCAPE_DEPTH             1069
#define IDC_LANDSCAPE_HEIGHT            1070
#define IDC_LANDSCAPE_BUILD             1071
#define IDC_TRANSPARENCY_COLOUR         1072
#define IDC_BACK_TEXTUREFILENAME        1073
#define IDC_MODELMAP_TEXTURE            1074
#define IDC_MODELMAP_SELECT             1075
#define IDC_BACKGROUND_TEXTURE          1076
#define IDC_BUTTON1                     1077
#define IDC_UPDATEBUTTON                1077
#define IDC_BACK_COLOUR                 1078
#define IDC_FOREGROUND_TEXTURE          1078
#define IDC_SELECT_BACK_COLOUR          1079
#define IDC_FORE_TEXTUREFILENAME        1079
#define IDC_SELECT_SIDE_COLOUR          1080
#define IDC_BULLET_LOAD                 1081
#define IDC_SELECT_SIDE_COLOURTOP       1082
#define IDC_SIDE_COLOUR                 1083
#define IDC_ACTIVE_BULLETS              1084
#define IDC_SIDE_COLOURTOP              1085
#define IDC_SELECT_SIDE_COLOUR2         1086
#define IDC_SELECT_FORE_COLOUR          1087
#define IDC_TTL                         1088
#define IDC_SELECT_SIDE_COLOURBOTTOM    1089
#define IDC_FORE_COLOUR                 1090
#define IDC_BULLET_SPEED                1091
#define IDC_SIDE_COLOURBOTTOM           1092
#define IDC_EDIT_GRAVITY                1093
#define IDC_DROP_OFF_FACTOR             1094
#define IDC_MAX_MISSILES                1095
#define IDC_WIDTH                       1096
#define IDC_HEIGHT                      1097
#define ID_WINDOWS_SCENEGRAPH           32773
#define ID_WINDOWS_LOGWINDOW            32774
#define ID_WINDOWS_COMPONENTLIBRARY     32775
#define ID_WINDOWS_PROPERTIES           32776
#define ID_FILE_SAVEAS                  32779
#define ID_VIEW_WIREFRAME               32780
#define ID_VIEW_CULLCCW                 32782

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
